[build]
  command = "npm run build"
  publish = "dist/mi_app/browser"

[[redirects]]
  from = "/api/*"
  to = "https://mi-app-ru0u.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200