services:
  - type: web
    name: vetcore-api
    env: node
    rootDir: .
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run api
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: MONGO_MAX_POOL_SIZE
        value: "20"
      - key: MONGO_MIN_POOL_SIZE
        value: "2"
